global using UserManagementService.Data;
global using UserManagementService.DTOs;
global using UserManagementService.Enums;
global using UserManagementService.Events;
global using UserManagementService.Events.Contracts;
global using UserManagementService.Helpers;
global using UserManagementService.Models;
global using UserManagementService.Services;
global using UserManagementService.Services.Contracts;
